language: python
python:
    - 2.6
    - 2.7
    - 3.2
    - 3.3
    - 3.4
    - 3.5-dev
    - nightly
install:
    - pip install coveralls
    - python setup.py build
script:
    - coverage run --source=mwparserfromhell setup.py -q test
after_success:
    - coveralls
env:
  matrix:
    - WITHOUT_EXTENSION=0
    - WITHOUT_EXTENSION=1
